
add_library(Qt5::QEglFSSurfaceFlingerIntegrationPlugin MODULE IMPORTED)

_populate_Gui_plugin_properties(QEglFSSurfaceFlingerIntegrationPlugin RELEASE "egldeviceintegrations/libqeglfs-surfaceflinger-integration.so")

list(APPEND Qt5Gui_PLUGINS Qt5::QEglFSSurfaceFlingerIntegrationPlugin)
